=== dannywly/phpTest/document/api/schemas/store/goods/create/post/schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "type": "object",
  "properties": {
    "storeId": {
      "type": "string",
      "required": true,
      "description": "门店Id"
    },
    "shelfId": {
      "type": "string",
      "required": true,
      "description": "货架Id"
    },
    "productId": {
      "type": "string",
      "required": true,
      "description": "商品Id"
    },
     "specs": {
      "type": "array",
      "required": true,
      "description": "specsId 为规格属性id用逗号隔开"
    }
  }
}

=== dannywly/phpTest/document/api/examples/store/goods/create/post/request.json
{
    "storeId": "5784890eaf831c15118b4593",
    "shelfId": "57884fcbaf831ce0698b456b",
    "productId": "576cf2a5af831c68678b4567",
    "specs": [
        {
            "specsId": "d6d453e3-b203-aa5f-81b8-c208c63ad094,dad4a484-19b9-4b28-c497-bf4d8ef5de4e",
            "prices": 12
        },
        {
            "specsId": "d6d453e3-b203-aa5f-81b8-c208c63ad094,8f9bea29-5df2-8b53-a905-e1121edbb37a",
            "prices": 2
        },
        {
            "specsId": "b70e01a6-0cea-4856-9465-f1232b4db56d,dad4a484-19b9-4b28-c497-bf4d8ef5de4e",
            "prices": 12
        },
        {
            "specsId": "b70e01a6-0cea-4856-9465-f1232b4db56d,8f9bea29-5df2-8b53-a905-e1121edbb37a",
            "prices": 2
        }
    ]
}
